fix webpack generating window reference in build
The current build uses webpack 4, which outputs an undefined
`window` reference and causes

```
ReferenceError: window is not defined
```

upon import via e.g. `require("cache-control-parser")` from
node. Updating the webpack config fixes the error after rebuild.
References:

- https://stackoverflow.com/a/58718315
- https://github.com/webpack/webpack/issues/6642
- https://webpack.js.org/configuration/output/#outputglobalobject